### ISSUE TITLE
npm run ios (or android) gets Error: Cannot find module 'xtend'

### ISSUE THREAD

**Issue by Rick49** [awslabs/aws-mobile-react-native-starter#61]
Following READ.ME, script seems to work through (sudo) npm i, until the 'npm run ios #npm run android'.  It fails the same way for npm run ios or android alone:

npm version 5.6.0
node version 8.9.4
awsmobile version 1.0.15
xtend appears to be installed globally, but not locally.

```
rick$ sudo npm run ios

> aws-mobile-react-native-sample@0.1.0 ios /Users/rick/Documents/JuvaCare/jcg
> react-native run-ios

module.js:540
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rick/Documents/JuvaCare/jcg/node_modules/metro-bundler/src/worker-farm/lib/farm.js:24:16)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rick/Documents/JuvaCare/jcg/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-mobile-react-native-sample@0.1.0 ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-mobile-react-native-sample@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rick/.npm/_logs/2018-02-18T18_32_54_212Z-debug.log

```

**Comment by smustaoglu** [comment]
use npm 4.2
define ANDROID_HOME
run "react-native run-ios"

**Comment by Rick49** [comment]
Thanks - I just tried that, and got the same error.   Any other ideas?  I've tried wiping out the installation and restarting a few times, but no luck...

**Comment by Rick49** [comment]
Ah, wait - I didn't realize I needed to run npm i again - after I did that it seems like it's working.

Thanks
